# -*- coding: utf-8 -*-
"""Jenica password generator ai model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F01SgI9EH5VjsD3p0BliUt4mzrKya3y9
"""

import random
import string

print("Choose what you want in your password:")
use_lower = input("Include lowercase letters? (y/n): ").lower()
use_upper = input("Include uppercase letters? (y/n): ").lower()
use_digits = input("Include digits? (y/n): ").lower()
use_symbols = input("Include symbols? (y/n): ").lower()

length = int(input("Enter password length: "))

# Build the character pool based on user choices
characters = ""

if use_lower == "y":
    characters += string.ascii_lowercase
if use_upper == "y":
    characters += string.ascii_uppercase
if use_digits == "y":
    characters += string.digits
if use_symbols == "y":
    characters += string.punctuation

# If the user selects nothing
if characters == "":
    print("Error: You must select at least one character type!")
else:
    password = "".join(random.choice(characters) for _ in range(length))
    print("\nYour generated password is:", password)